import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { useState } from "react";
import toast from "react-hot-toast";
import "react-phone-number-input/style.css";
import PhoneInput from "react-phone-number-input";

export default function Vote() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-br from-[#18229B] to-[#FF5C00]">
        <main className="flex min-h-screen flex-col items-center justify-center ">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              System Testing for <span className="text-[#FF5C00]">IAGD</span>{" "}
              Election
            </h1>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="/"
                target="_blank"
              >
                <h3 className="text-xl font-bold">
                  Haven&apos;t receive token yet? →
                </h3>
                <div className="text-lg">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Provident, ea!
                </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="/"
                target="_blank"
              >
                <h3 className="text-xl font-bold">See the candidates →</h3>
                <div className="text-lg">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                  Animi, rem!
                </div>
              </Link>
            </div>
          </div>
        </main>
        <main className="flex h-[720px]  justify-center">
          <FormInput />
        </main>
      </div>
    </>
  );
}

const FormInput = () => {
  const [voterToken, setVoterToken] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");

  const [isChecked, setIsChecked] = useState(false);

  const isFormInvalid = voterToken === "" || !phoneNumber;

  const { mutate, isLoading: isLoadingVerify } =
    api.vote.validateVoterToken.useMutation({
      onSuccess: () => {
        toast.success("Welcome!");
      },
      onError: (err) => {
        toast.error(err.message);
      },
    });

  const handleClickVerify = () => {
    mutate({ voterToken, phoneNumber });
  };

  const handleTokenChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setVoterToken(event.currentTarget.value);
  };

  const handlePhoneNumberChange = (phoneNumber: string) => {
    setPhoneNumber(phoneNumber);
  };

  const handleCheckboxChange = () => {
    setIsChecked(!isChecked);
  };

  return (
    <form className="w-screen ">
      <div className="mx-auto max-w-[520px] px-5  sm:w-[620px] md:w-[620px] lg:max-w-[920px]">
        <label className="mb-6 block text-2xl font-bold text-gray-900 dark:text-white md:mb-8 md:text-2xl lg:text-4xl">
          Please enter your phone number and voter token as shown in Voter List
        </label>
        <label className="text-md my-2 block font-semibold text-gray-900 dark:text-white md:text-lg ">
          Phone Number
        </label>
        <PhoneInput
          value={phoneNumber}
          onChange={handlePhoneNumberChange}
          className="text-md mb-4 block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 focus:border-blue-500 focus:ring-blue-500"
          defaultCountry="ID"
          international
          countryCallingCodeEditable={false}
        />
        <label className="text-md my-2 block font-semibold text-gray-900 dark:text-white  md:text-lg ">
          Voter Token
        </label>
        <input
          onChange={handleTokenChange}
          className="text-md block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-gray-900 focus:border-blue-500 focus:ring-blue-500"
          placeholder="voter token"
          type="password"
        />
        <div className="my-4 flex items-start justify-center align-middle">
          <input
            type="checkbox"
            checked={isChecked}
            onChange={handleCheckboxChange}
            className="focus:ring-3 mt-[3px] h-5 w-5 rounded border border-gray-300 bg-gray-50 focus:ring-blue-300 sm:mt-[4px]"
          />
          <p className="ml-4  text-sm font-bold text-gray-900 dark:text-gray-300 md:text-lg">
            By checking this box, I sincerely declare that I am the rightful
            owner of this phone number and token.
          </p>
        </div>
        <button
          type="button"
          className={`text-md transition-duration: 150ms; rounded-lg px-5 py-2.5 text-center font-medium text-white hover:bg-amber-600 focus:outline-none focus:ring-4 focus:ring-blue-300 sm:w-auto
          ${
            !isChecked || isLoadingVerify || isFormInvalid
              ? "bg-slate-800"
              : "bg-[#FF5C00]"
          }`}
          onClick={handleClickVerify}
          disabled={!isChecked || isLoadingVerify || isFormInvalid}
        >
          Verify Token
        </button>
      </div>
    </form>
  );
};
